# .github/workflows/deploy.yml

name: Deploy FastAPI to Google Cloud Run

on:
  push:
    branches:
      - main  # Triggers the workflow on pushes to the 'main' branch
      - dev
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 3: Configure Docker to use Google Cloud credentials
      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker gcr.io

      # Step 4: Build the Docker image
      - name: Build Docker Image
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/whatsappllm:${{ github.sha }}
          docker build -t $IMAGE .

      # Step 5: Push the Docker image to GCR
      - name: Push Docker Image to GCR
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/whatsappllm:${{ github.sha }}
          docker push $IMAGE
        # Ensure the image name matches the build step

      # Step 6: Deploy to Google Cloud Run
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: whatsappllm-service                              # Your Cloud Run service name
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/whatsappllm:${{ github.sha }}  # Image to deploy
          region: ${{ secrets.GCP_REGION }}                       # Deployment region
          platform: managed                                        # Fully managed Cloud Run
          allow_unauthenticated: true                              # Allow public access

      # Optional Step 7: Clean Up Docker Images (To save storage on the runner)
      - name: Clean Up Docker Images
        if: always()
        run: |
          docker image prune -f